*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep  3 17:57:19 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep  3 17:59:41 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x12bed30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x12bed30 pid: 3279 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 3279)
spawned uWSGI worker 1 (pid: 3281, cores: 2)
spawned uWSGI worker 2 (pid: 3282, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep  3 18:14:17 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x1c6f850
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1c6f850 pid: 3279 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 3279)
spawned uWSGI worker 1 (pid: 3385, cores: 2)
spawned uWSGI worker 2 (pid: 3386, cores: 2)
*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep  3 10:46:01 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x13fad30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x13fad30 pid: 3034 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 3034)
spawned uWSGI worker 1 (pid: 3036, cores: 2)
spawned uWSGI worker 2 (pid: 3037, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep  3 10:54:54 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x1d07850
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1d07850 pid: 3034 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 3034)
spawned uWSGI worker 1 (pid: 3144, cores: 2)
spawned uWSGI worker 2 (pid: 3145, cores: 2)
Internal Server Error: /
Traceback (most recent call last):
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 189, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2026, 'SSL connection error: protocol version mismatch')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 20, in _wrapped_view
    if test_func(request.user):
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 44, in <lambda>
    lambda u: u.is_authenticated,
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 54, in __getitem__
    return self._session[key]
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/sessions/backends/base.py", line 194, in _get_session
    self._session_cache = self.load()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 43, in load
    s = self._get_session_from_db()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/sessions/backends/db.py", line 34, in _get_session_from_db
    expire_date__gt=timezone.now()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2026, 'SSL connection error: protocol version mismatch')
Not Found: /favicon.ico
Internal Server Error: /users/login/
Traceback (most recent call last):
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
MySQLdb._exceptions.OperationalError: (2026, 'SSL connection error: protocol version mismatch')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/root/projects/wjgl/apps/users/views.py", line 30, in post
    user = authenticate(username=user_name, password=pass_word)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/backends.py", line 20, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    cursor = self.connection.cursor()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
    return self._cursor()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
    self.ensure_connection()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
    return Database.connect(**conn_params)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
    return Connection(*args, **kwargs)
  File "/root/.virtualenvs/wjgl/lib/python3.6/site-packages/MySQLdb/connections.py", line 164, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (2026, 'SSL connection error: protocol version mismatch')
Tue Sep  3 11:00:29 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Sep  3 11:00:29 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Sep  3 11:00:29 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Tue Sep  3 11:00:29 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep  3 11:12:59 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x100ed30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x100ed30 pid: 5710 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5710)
spawned uWSGI worker 1 (pid: 5712, cores: 2)
spawned uWSGI worker 2 (pid: 5713, cores: 2)
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Forbidden (CSRF token missing or incorrect.): /files/upload/
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep  4 10:34:31 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 7331
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x1bd9850
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep  4 10:38:23 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0xc2dd30
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xc2dd30 pid: 3237 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 3237)
spawned uWSGI worker 1 (pid: 3239, cores: 2)
spawned uWSGI worker 2 (pid: 3240, cores: 2)
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep  4 11:32:13 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x14468a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x14468a0 pid: 3237 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 3237)
spawned uWSGI worker 1 (pid: 3435, cores: 2)
spawned uWSGI worker 2 (pid: 3436, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep  4 12:14:08 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x29118a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x29118a0 pid: 3237 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 3237)
spawned uWSGI worker 1 (pid: 3572, cores: 2)
spawned uWSGI worker 2 (pid: 3573, cores: 2)
Wed Sep  4 12:16:25 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep  4 12:16:25 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep  4 12:16:25 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep  4 12:16:25 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep  4 12:16:57 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x23ded80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x23ded80 pid: 3609 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 3609)
spawned uWSGI worker 1 (pid: 3611, cores: 2)
spawned uWSGI worker 2 (pid: 3612, cores: 2)
Wed Sep  4 13:20:08 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep  4 13:20:08 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep  4 13:20:08 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep  4 13:20:08 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Fri Sep  6 14:59:10 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x25e5d80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x25e5d80 pid: 4002 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 4002)
spawned uWSGI worker 1 (pid: 4004, cores: 2)
spawned uWSGI worker 2 (pid: 4005, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep 11 09:47:11 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x19e28a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x19e28a0 pid: 4002 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 4002)
spawned uWSGI worker 1 (pid: 25208, cores: 2)
spawned uWSGI worker 2 (pid: 25209, cores: 2)
Wed Sep 11 09:47:45 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep 11 09:47:45 2019 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep 11 09:47:45 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Wed Sep 11 09:47:45 2019 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Wed Sep 11 09:48:07 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0xf30d80
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xf30d80 pid: 25224 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 25224)
spawned uWSGI worker 1 (pid: 25226, cores: 2)
spawned uWSGI worker 2 (pid: 25227, cores: 2)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /root/projects/wjgl/conf
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8000)
running /root/.virtualenvs/wjgl/bin/uwsgi
[uWSGI] getting INI configuration from wjgl_uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Sep 24 10:13:30 2019] ***
compiled with version: 4.4.7 20120313 (Red Hat 4.4.7-23) on 03 September 2019 09:14:19
os: Linux-2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018
nodename: filetrans
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /root/projects/wjgl/conf
detected binary path: /root/.virtualenvs/wjgl/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /root/projects/wjgl
your processes number limit is 31312
your memory page size is 4096 bytes
 *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.6.8 (default, Sep  3 2019, 16:58:17)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-23)]
Set PythonHome to /root/.virtualenvs/wjgl
Python main interpreter initialized at 0x130a8a0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 250128 bytes (244 KB) for 4 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x130a8a0 pid: 25224 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 25224)
spawned uWSGI worker 1 (pid: 78975, cores: 2)
spawned uWSGI worker 2 (pid: 78976, cores: 2)
